# -*- coding: utf-8 -*-
"""Spotify_datasetcleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0FlWrbkdOzFXPpiSdXrvUKPGOeaX83U
"""

# Imporing pandas libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import warnings
warnings.simplefilter("ignore")

df=pd.read_csv('/content/dataset.csv')

df.shape

df.head()

df.tail()

df.isna().sum()

df.dtypes

df.drop(columns=['key','acousticness'],inplace=True)

df.columns.unique()

df.track_genre.unique()

df.to_csv('spotify_dataset_new.csv')

